name: Lobsters Data Import

on:
  push:
    paths:
    - .github/workflows/lobsters.yml
  workflow_dispatch:
  schedule:
    - cron: '*/60 * * * *'
  
jobs: 
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch newest
        uses: githubocto/flat@v3
        with:
          http_url: https://lobste.rs/newest.json
          downloaded_filename: newest.json
      - name: Neo4j import
        uses: johnymontana/flat-graph@v1.2
        with:
          neo4j-user: ${{secrets.NEO4J_USER}}
          neo4j-password: ${{secrets.NEO4J_PASSWORD}}
          neo4j-uri: ${{secrets.NEO4J_URI}}
          filename: 'newest.json'
          cypher-query: >
              UNWIND $value AS article
              MERGE (u:User {username: article.submitter_user.username})
                SET u.created = DateTime(article.submitter_user.created_at),
                    u.karma = article.submitter_user.karma,
                    u.about = article.submitter_user.about,
                    u.avatar = "https://lobste.rs" + article.submitter_user.avatar_url
              MERGE (i:User {username:article.submitter_user.invited_by_user})
              MERGE (i)<-[:INVITED_BY]-(u)
              MERGE (a:Article {id: article.short_id})
                SET a.url           = article.url,
                    a.id_url        = article.short_id_url,
                    a.created_at    = article.created_at,
                    a.title         = article.title,
                    a.score         = article.score,
                    a.flags         = article.flags,
                    a.comment_count = article.comment_count,
                    a.description   = article.description,
                    a.comments_url  = article.comments_url
              MERGE (u)-[:SUBMITTED]->(a)
              WITH article, a
              UNWIND article.tags AS tag
              MERGE (t:Tag {name: tag})
              MERGE (a)-[:HAS_TAG]->(t)  
